import { JetBrains_Mono } from "next/font/google";
import "./globals.css";


import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
import { TypewriterEffectDemo } from "./page";
import { Import } from "lucide-react";


const jetbrainsMono1 = JetBrains_Mono ({
  subsets: ["latin"],
  weight: ["100", "200","300", "400", "500", "600", "800", ],
  variable: "--font-jetbrainsMono1",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={jetbrainsMono1.variable}>
        <Header />
        
        <StairTransition />
        <PageTransition> {children} </PageTransition>
        {/* <TypewriterEffectDemo />  */}
       
        </body>
    </html>
  );
}

